<?php

return [
    [
        'slug' => 'ana-silva',
        'initials' => 'AS',
        'name' => 'Ana Silva',
        'role' => 'Chefe de Operações',
        'org' => 'Organização',
        'topic' => 'Reforço da competência operacional através de práticas modernas de segurança.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Ana Silva lidera iniciativas de segurança operacional e melhoria contínua.',
    ],
    [
        'slug' => 'joao-mendes',
        'initials' => 'JM',
        'name' => 'João Mendes',
        'role' => 'Engenheiro Sénior',
        'org' => 'Empresa',
        'topic' => 'Sistemas CNS/ATM resilientes: fiabilidade, manutenção e modernização.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'João Mendes é especialista em manutenção, modernização e resiliência de sistemas críticos.',
    ],
    [
        'slug' => 'carla-nunes',
        'initials' => 'CN',
        'name' => 'Carla Nunes',
        'role' => 'Gestora de Programas',
        'org' => 'Instituição',
        'topic' => 'Governação, normas e transformação sustentável em infraestruturas críticas.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Carla Nunes gere programas de transformação e governação em infraestruturas críticas.',
    ],
    [
        'slug' => 'joao-mendes',
        'initials' => 'JM',
        'name' => 'João Mendes',
        'role' => 'Engenheiro Sénior',
        'org' => 'Empresa',
        'topic' => 'Sistemas CNS/ATM resilientes: fiabilidade, manutenção e modernização.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'João Mendes é especialista em manutenção, modernização e resiliência de sistemas críticos.',
    ],
    [
        'slug' => 'carla-nunes',
        'initials' => 'CN',
        'name' => 'Carla Nunes',
        'role' => 'Gestora de Programas',
        'org' => 'Instituição',
        'topic' => 'Governação, normas e transformação sustentável em infraestruturas críticas.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Carla Nunes gere programas de transformação e governação em infraestruturas críticas.',
    ],
    [
        'slug' => 'joao-mendes',
        'initials' => 'JM',
        'name' => 'João Mendes',
        'role' => 'Engenheiro Sénior',
        'org' => 'Empresa',
        'topic' => 'Sistemas CNS/ATM resilientes: fiabilidade, manutenção e modernização.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'João Mendes é especialista em manutenção, modernização e resiliência de sistemas críticos.',
    ],
    [
        'slug' => 'carla-nunes',
        'initials' => 'CN',
        'name' => 'Carla Nunes',
        'role' => 'Gestora de Programas',
        'org' => 'Instituição',
        'topic' => 'Governação, normas e transformação sustentável em infraestruturas críticas.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Carla Nunes gere programas de transformação e governação em infraestruturas críticas.',
    ],
    [
        'slug' => 'joao-mendes',
        'initials' => 'JM',
        'name' => 'João Mendes',
        'role' => 'Engenheiro Sénior',
        'org' => 'Empresa',
        'topic' => 'Sistemas CNS/ATM resilientes: fiabilidade, manutenção e modernização.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'João Mendes é especialista em manutenção, modernização e resiliência de sistemas críticos.',
    ],
    [
        'slug' => 'carla-nunes',
        'initials' => 'CN',
        'name' => 'Carla Nunes',
        'role' => 'Gestora de Programas',
        'org' => 'Instituição',
        'topic' => 'Governação, normas e transformação sustentável em infraestruturas críticas.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Carla Nunes gere programas de transformação e governação em infraestruturas críticas.',
    ],
    [
        'slug' => 'joao-mendes',
        'initials' => 'JM',
        'name' => 'João Mendes',
        'role' => 'Engenheiro Sénior',
        'org' => 'Empresa',
        'topic' => 'Sistemas CNS/ATM resilientes: fiabilidade, manutenção e modernização.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'João Mendes é especialista em manutenção, modernização e resiliência de sistemas críticos.',
    ],
    [
        'slug' => 'carla-nunes',
        'initials' => 'CN',
        'name' => 'Carla Nunes',
        'role' => 'Gestora de Programas',
        'org' => 'Instituição',
        'topic' => 'Governação, normas e transformação sustentável em infraestruturas críticas.',
        'photo' => 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?auto=format&fit=crop&w=1200&q=80',
        'bio' => 'Carla Nunes gere programas de transformação e governação em infraestruturas críticas.',
    ],

    // Se quiseres repetir, repete aqui (mas ideal é não duplicar)
];
