name: Deploy Laravel via FTPS to ifatseaarm26.aata.ao

on:
  push:
    branches:
      - main   # troque para master se for o seu caso

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Garante que NUNCA vai tentar subir .git/.github
      - name: Remove git folders from workspace
        run: |
          rm -rf .git
          rm -rf .github

      - name: Deploy to FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # pela mensagem TLSSocket no erro, você está em FTPS
          protocol: ftps
          port: 21

          # mais folga para servidores lentos
          timeout: 300000

          # SUA PASTA (conforme a imagem)
          server-dir: /ifatseaarm26.aata.ao/

          exclude: |
            **/.git*
            **/.git/**
            **/.github/**
            **/vendor/**
            **/node_modules/**
            **/tests/**
            **/.env
            **/.env.*
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**