name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove unwanted files
        run: |
          rm -rf .git .github node_modules tests vendor
          rm -f .env
          rm -f .env.*

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy with lftp
        run: |
          lftp -e "
          set ftp:ssl-allow true;
          set ssl:verify-certificate no;
          set ftp:passive-mode true;
          set net:timeout 120;
          set net:max-retries 2;
          mirror -R --delete --verbose \
            --exclude-glob .git* \
            --exclude-glob .github/** \
            --exclude-glob node_modules/** \
            --exclude-glob vendor/** \
            --exclude-glob tests/** \
            --exclude-glob .env \
            --exclude-glob .env.* \
            --exclude-glob storage/logs/** \
            --exclude-glob storage/framework/cache/** \
            --exclude-glob storage/framework/sessions/** \
            --exclude-glob storage/framework/views/** \
            ./ /ifatseaarm26.aata.ao/;
          bye
          " -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}"